# This file describes a blueprint for use in Crafter Studio

# The version of this type of this file
descriptorVersion: 1

# Describe the blueprint
blueprint:
  id: org.craftercms.blueprint.videoCenter
  name: Video Center Blueprint
  tags: blueprint,video center
  version:
    major: 1
    minor: 0
    patch: 0
  description: |
    Video center blueprint
  website:
    name: Video Center Blueprint
    url: https://vc.craftercloud.io
  media:
    screenshots:
      - screenshot:
          title: Home page
          description: Screenshot of the home page
          url: /studio/static-assets/images/blueprints/video-center/vc1.png
      - screenshot:
          title: Featured videos page
          description: Screenshot of the featured videos page
          url: /studio/static-assets/images/blueprints/video-center/vc2.png
      - screenshot:
          title: Player page
          description: Screenshot of the player page
          url: /studio/static-assets/images/blueprints/video-center/vc3.png
      - screenshot:
          title: Search page
          description: Screenshot of the search page
          url: /studio/static-assets/images/blueprints/video-center/vc4.png
    developer:
      company:
        name: Crafter Software
        email: info@craftersoftware.com
        url: https://craftersoftware.com/
  build:
    id: c3d2a5444e6a24b5e0481d6ba87901d0b02716c8
    date: 2019-03-18T00:00:00Z
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  craftercmsVersionsSupported:
    - version: 3.1.0
  searchEngine: Elasticsearch
